### ISSUE TITLE
automatically use vue(tify) locales

### ISSUE THREAD

**Issue by MartinX3** [mcibique/vue-date-fns#19]
Is there a way to automatically use already defined and dynamically changed locales?
Some kind of automatic mapping since the locale names are the same.

https://vuetifyjs.com/en/features/internationalization/
https://vuetifyjs.com/en/features/internationalization/#vue-i18n

**Comment by mcibique** [comment]
I don't think so. As this is just a wrapper around date-fns, it only supports the locales in the format requested by date-fns lib (https://date-fns.org/v2.28.0/docs/Locale), you can find examples in their repo (https://github.com/date-fns/date-fns/tree/v2.28.0/src/locale).
